default: &default
  adapter: mysql2
  host: localhost
  username: root
  #local
  password: 
  #use password while in gcp
  #password: root

development:
  <<: *default
  database: scm_development

test:
  <<: *default
  database: scm_test

production:
  adapter: mysql2
  database: scm_production
